[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10"
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-native-tls", "postgres"] }
toml = "0.8.21"
url = { version = "2.5.4", features = ["serde"] }

[dependencies.tokio]
version = "1.44"
features = ["full"]
