version: '3.5'
volumes:
  gorb-backend:
  gorb-database:
networks:
  gorb:
services:
  backend:
    image: gorb/backend
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - gorb
    volumes:
      - gorb-backend:/gorb
    environment:
      #- RUST_LOG=debug
      # This should be changed to the public URL of the server!
      - URL=http://localhost:8080
      - DATABASE_USERNAME=gorb
      - DATABASE_PASSWORD=gorb
      - DATABASE=gorb
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      # These can be set to use a CDN, if they are not set then files will be stored locally
      #- BUNNY_API_KEY=your_storage_zone_password_here
      #- BUNNY_ENDPOINT=Frankfurt
      #- BUNNY_ZONE=gorb
      #- BUNNY_CDN_URL=https://cdn.gorb.app
  database:
    image: postgres:16
    restart: always
    networks:
      - gorb
    volumes:
      - gorb-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gorb
      - POSTGRES_PASSWORD=gorb
      - POSTGRES_DB=gorb
  valkey:
    image: valkey/valkey
    restart: always
    networks:
      - gorb
