version: '3.5'
volumes:
  gorb-backend:
  gorb-database:
networks:
  gorb:
services:
  backend:
    image: git.gorb.app/gorb/backend:main
    restart: always
    ports:
      - 8080:8080
    networks:
      - gorb
    volumes:
      - gorb-backend:/gorb
    environment:
      #- RUST_LOG=debug
      - WEB_FRONTEND_URL=https://gorb.app/web/
      - DATABASE_USERNAME=gorb
      - DATABASE_PASSWORD=gorb
      - DATABASE=gorb
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - BUNNY_API_KEY=your_storage_zone_password_here
      - BUNNY_ENDPOINT=Frankfurt
      - BUNNY_ZONE=gorb
      - BUNNY_CDN_URL=https://cdn.gorb.app
      - MAIL_ADDRESS=Gorb <noreply@gorb.app>
      - MAIL_TLS=tls
      - SMTP_SERVER=mail.gorb.app
      - SMTP_USERNAME=your_smtp_username
      - SMTP_PASSWORD=your_smtp_password
  database:
    image: postgres:16
    restart: always
    networks:
      - gorb
    volumes:
      - gorb-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gorb
      - POSTGRES_PASSWORD=gorb
      - POSTGRES_DB=gorb
  valkey:
    image: valkey/valkey
    restart: always
    networks:
      - gorb
