when:
  - event: push
    branch: main

steps:
  - name: container-build-and-publish
    image: docker
    commands:
      - docker login --username radical --password $PASSWORD git.gorb.app
      - docker buildx build --platform linux/amd64,linux/arm64 --rm --push -t git.gorb.app/gorb/backend:main .
    environment:
      PASSWORD:
        from_secret: docker_password
    volumes:
      - /var/run/podman/podman.sock:/var/run/docker.sock
